show_page:
  name: Send a page to Divoom
  description: Display a specified page on the Divoom. Please select the "... Current Page" entity of the device.
  target:
    entity:
      domain: sensor
      integration: divoom
  fields:
    page_data:
      name: Page Data
      description: "Consider this as one page, so start at 'page_type=something' (ignore the '-' in front)."
      required: true
      example: "page_type: clock\n enabled: true\n id: 182"
      selector:
        object:
    duration:
      name: Duration of the notification
      description: "This will be the time the message is displayed on the device. Default: the device's scan_time in the config."
      required: false
      example: "10"
      selector:
        number:
          min: 1
          max: 9999
          unit_of_measurement: seconds
          mode: box
show_message:
  name: Send a message to Divoom
  description: Display message on the Divoom
  target:
    entity:
      domain: light
      integration: divoom
  fields:
    message:
      name: Message
      description: "message..."
      required: true
      example: "test"
      selector:
        text:
    duration:
      name: Duration of the notification
      description: "This will be the time the message is displayed on the device."
      required: true
      example: "10"
      selector:
        number:
          min: 1
          max: 9999
          unit_of_measurement: seconds
          mode: box

countdown:
  name: Countdown Divoom
  description: Display countdown on the Divoom
  target:
    entity:
      domain: light
      integration: divoom
  fields:
    minute:
      name: Minute
      description: "the countdown’s minute"
      required: true
      example: "10"
      selector:
        number:
          min: 0
          max: 9999
          unit_of_measurement: minutes
          mode: box
    second:
      name: Second
      description: "the countdown’s second"
      required: true
      example: "0"
      selector:
        number:
          min: 0
          max: 9999
          unit_of_measurement: seconds
          mode: box

stopwatch:
  name: Stopwatch Divoom
  description: Display stopwatch on the Divoom
  target:
    entity:
      domain: light
      integration: divoom
  fields:
    mode:
      name: Mode
      description: "reset, start, stop"
      required: true
      example: "start"
      selector:
        text: